action.configuration.eca_menu_enable_menu_item:
  type: mapping
  label: 'Menu Item: Enable or Disable'
  mapping:
    menu_item:
      type: string
      label: 'ID of menu item'
    enabled:
      type: boolean
      label: 'Enable'
    object:
      type: string
      label: 'Token name holding the entity'
