name: Byte
type: Site
description: 'Designed for a SaaS product website, this template includes landing pages, a blog, newsletter sign up and other features.'
recipes:
  - drupal_cms_blog
  - drupal_cms_forms
  - drupal_cms_starter
  # Put SEO tools last so that it adds its fields to whatever content types were
  # created by the preceding recipes.
  - drupal_cms_seo_tools
install:
  - project_browser
  - ui_icons_menu
config:
  strict: false
  import:
    system:
      - system.menu.footer
  actions:
    # Sitemap blocks aren't really useful for page building; the sitemap is
    # available at its own page anyway.
    canvas.component.block.sitemap:
      disable: []
    # Blog posts cannot render properly without a featured image, so
    # make the field required.
    field.field.node.blog.field_featured_image:
      setRequired: true
    # Allow Canvas to render all content types.
    field.storage.node.field_component_tree:
      addToAllBundles:
        label: Components
        description: Stores a component tree for Canvas.
    # Use Mercury's dark color scheme by default.
    mercury.settings:
      simpleConfigUpdate:
        scheme: byte-dark
        logo:
          use_default: false
          path: 'public://byte-logo.svg'
    # Only show basic metatag fields on Canvas pages.
    metatag.settings:
      simpleConfigUpdate:
        entity_type_groups:
          canvas_page:
            canvas_page:
              basic: basic
    # Allow basic pages to go into the main menu, or the footer.
    node.type.page:
      setThirdPartySettings:
        -
          module: menu_ui
          key: available_menus
          value:
            - main
            - footer
            - utility
        -
          module: menu_ui
          key: parent
          value: 'main:'
    project_browser.admin_settings:
      simpleConfigUpdate:
        # @see recommended.yml
        enabled_sources.recommended.uri: 'https://git.drupalcode.org/api/v4/projects/157093/repository/files/byte%2Frecommended.yml/raw?ref=HEAD'
    system.site:
      simpleConfigUpdate:
        # The Home page, built in Canvas.
        page.front: '/home'
    views.view.blog:
      setProperties:
        # Opt this view into the grid-snap styling that Mercury offers.
        tag: 'snap'
        # The default display should show 6 items per page, with a full pager.
        display.default.display_options.pager:
          type: full
          options:
            offset: 0
            pagination_heading_level: h4
            items_per_page: 6
            total_pages: null
            id: 0
            tags:
              next: ››
              previous: ‹‹
              first: '« First'
              last: 'Last »'
            expose:
              items_per_page: false
              items_per_page_label: 'Items per page'
              items_per_page_options: '5, 10, 25, 50'
              items_per_page_options_all: false
              items_per_page_options_all_label: '- All -'
              offset: false
              offset_label: Offset
            quantity: 9
        # Remove header text.
        display.latest.display_options.header: []
        # Hide the tags filter.
        display.all.display_options.filters.field_tags_target_id.exposed: false
    webform.webform.contact_form:
      setProperties:
        settings.confirmation_type: modal
extra:
  recipe_installer_kit:
    finish_url: '/admin/dashboard/welcome'
