id: node.blog.card
status: true
content_entity_type_id: node
content_entity_type_bundle: blog
content_entity_type_view_mode: card
dependencies:
  config:
    - canvas.component.sdc.mercury.card
    - core.entity_view_mode.node.card
    - field.field.media.image.field_media_image
    - field.field.node.blog.field_description
    - field.field.node.blog.field_featured_image
    - image.style.canvas_parametrized_width
    - media.type.image
    - node.type.blog
  module:
    - file
    - media
    - node
    - options
component_tree:
  - uuid: c8e8a6d9-6b30-4cf0-a8df-299f290da17d
    component_id: sdc.mercury.card
    component_version: a1a6d0ff59cbd502
    inputs:
      heading_text:
        sourceType: dynamic
        expression: 'ℹ︎␜entity:node:blog␝title␞␟value'
      level: 3
      url:
        sourceType: host-entity-url
      media:
        sourceType: dynamic
        expression: 'ℹ︎␜entity:node:blog␝field_featured_image␞␟{src↝entity␜␜entity:media:image␝field_media_image␞␟entity␜␜entity:file␝uri␞␟url,alt↝entity␜␜entity:media:image␝field_media_image␞␟alt}'
      text:
        sourceType: dynamic
        expression: 'ℹ︎␜entity:node:blog␝field_description␞␟value'
      style: framed
      orientation: stacked
exposed_slots: {  }
