#!/usr/bin/env sh

## Description: Wrapper around the normal rebuild function with added stuff.
## Usage: demo-setup
## Example: "ddev demo-setup"

# Always delete
ddev delete -O -y

# Drupal CMS
ddev start

# Sleep because Mutagen is slow to notice changes.
sleep 5

# Install
ddev drush si drupal_cms_installer installer_site_template_form.add_ons=byte --account-pass=admin --site-name="2025 Demo" -y
# Install byte
#ddev install-byte

# Composer stuff
ddev composer require 'drupal/ai:1.2.x-dev@dev' \
'drupal/ai_agents:1.2.x-dev@dev' \
'drupal/ai_provider_openai:1.2.x-dev@dev' \
'drupal/ai_simple_pdf_to_text:^1.0@alpha' \
'drupal/ai_vdb_provider_milvus:1.1.x-dev@dev' \
'drupal/page_cache_exclusion:^1.0' \
'drupal/pexels_ai:^1.0@alpha' \
'jfcherng/php-diff:^6.0'

ddev drush cr
# Install the AI stuff.
ddev drush recipe ../custom_recipes/canvas_ai_setup
ddev drush cr
# Add all images after to make sure they are indexed correctly.
ddev drush recipe ../custom_recipes/media_images
# Add Aidan's manual pages
ddev drush recipe ../custom_recipes/new_canvas_page
# Always flush the cache
ddev drush cr

# Index the AI stuff
ddev drush sapi-i

echo "Visit https://v2025demo.ddev.site/canvas and login with user 'admin' and password 'admin' to see the demo page."
echo "After login, you click New and New Page to create a new page from AI."
